import { useMemo, useState } from 'react'
import { useStaff, usePrintRecords, useSettings, buildPersonSummary, rs } from '../lib/data'
import { SectionTitle } from './shared'
import { field, label, select, primaryBtn } from './formStyles'

export default function BillGenerator() {
  const { staff } = useStaff()
  const { records } = usePrintRecords({})
  const { settings } = useSettings()
  const [mode, setMode] = useState('individual') // individual | all
  const [personId, setPersonId] = useState('')
  const [billScope, setBillScope] = useState('summary') // summary | detailed

  const personRows = useMemo(() => buildPersonSummary(staff, records), [staff, records])
  const personsWithPending = personRows.filter(r => r.pending > 0)
  const selectedPerson = personRows.find(r => r.key === personId)

  const billDate = new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' })
  const bh = settings.bill_header || {}
  const officeName = bh.office_name || 'State Life Insurance Corporation of Pakistan'
  const areaName = bh.area_name || 'Area 9219'
  const address = bh.address || 'Jhang Zone'
  const contact = bh.contact || ''

  function getDetailedRecords(personKey) {
    return records.filter(r => {
      if (!personKey) return false
      if (personKey.startsWith('other:')) return !r.person_id && r.other_person_name === personKey.replace('other:', '')
      return r.person_id === personKey && r.status !== 'Paid'
    }).sort((a, b) => a.entry_date.localeCompare(b.entry_date))
  }

  function printBill() {
    const personsForBill = mode === 'all' ? personsWithPending : (selectedPerson ? [selectedPerson] : [])
    if (personsForBill.length === 0) return

    let billHtml = ''

    if (billScope === 'summary') {
      // ── SUMMARY FORMAT: one row per person ──────────────────────────
      const rows = personsForBill.map(p => `
        <tr>
          <td>${p.name}</td>
          <td>${p.designation || '—'}</td>
          <td class="right">${p.copies}</td>
          <td class="right">Rs. ${Math.round(p.billed).toLocaleString('en-PK')}</td>
          <td class="right">Rs. ${Math.round(p.received).toLocaleString('en-PK')}</td>
          <td class="right pending"><strong>Rs. ${Math.round(p.pending).toLocaleString('en-PK')}</strong></td>
        </tr>
      `).join('')

      const totalPending = personsForBill.reduce((s, p) => s + p.pending, 0)
      const totalBilled = personsForBill.reduce((s, p) => s + p.billed, 0)
      const totalReceived = personsForBill.reduce((s, p) => s + p.received, 0)

      billHtml = `
        <div class="bill-page">
          <div class="bill-header">
            <div class="org-name">${officeName}</div>
            <div class="org-sub">${areaName} · ${address}${contact ? ' · ' + contact : ''}</div>
            <div class="bill-title">PENDING PAYMENT SUMMARY</div>
          </div>
          <div class="bill-meta">
            <span><strong>Date:</strong> ${billDate}</span>
            <span><strong>Persons:</strong> ${personsForBill.length}</span>
          </div>
          <table class="bill-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Designation</th>
                <th class="right">Copies</th>
                <th class="right">Total Billed</th>
                <th class="right">Received</th>
                <th class="right">Balance Due</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
            <tfoot>
              <tr class="total-row">
                <td colspan="2"><strong>TOTAL</strong></td>
                <td></td>
                <td class="right"><strong>Rs. ${Math.round(totalBilled).toLocaleString('en-PK')}</strong></td>
                <td class="right"><strong>Rs. ${Math.round(totalReceived).toLocaleString('en-PK')}</strong></td>
                <td class="right pending"><strong>Rs. ${Math.round(totalPending).toLocaleString('en-PK')}</strong></td>
              </tr>
            </tfoot>
          </table>
          <div class="bill-footer">
            <div class="sig-box"><div class="sig-line"></div><div>Clerk Signature</div></div>
            <div class="sig-box"><div class="sig-line"></div><div>Manager Signature</div></div>
          </div>
          <div class="print-note">Generated by PrintDesk · ${billDate} · Area 9219</div>
        </div>
      `
    } else {
      // ── DETAILED FORMAT: one section per person ──────────────────────
      billHtml = personsForBill.map((person, pi) => {
        const recs = getDetailedRecords(person.key)
        return `
          ${pi > 0 ? '<div class="page-break"></div>' : ''}
          <div class="bill-page">
            <div class="bill-header">
              <div class="org-name">${officeName}</div>
              <div class="org-sub">${areaName} · ${address}${contact ? ' · ' + contact : ''}</div>
              <div class="bill-title">PHOTOCOPY & PRINT CHARGES</div>
            </div>
            <div class="bill-meta">
              <span><strong>For:</strong> ${person.name} (${person.designation || ''})</span>
              <span><strong>Date:</strong> ${billDate}</span>
            </div>
            <table class="bill-table">
              <thead>
                <tr><th>#</th><th>Date</th><th>Description</th><th class="right">Amount</th><th class="right">Paid</th><th class="right">Due</th></tr>
              </thead>
              <tbody>
                ${recs.map((r, i) => `
                  <tr>
                    <td>${i + 1}</td>
                    <td>${r.entry_date}</td>
                    <td>${r.description || ''}</td>
                    <td class="right">Rs. ${Math.round(r.amount).toLocaleString('en-PK')}</td>
                    <td class="right">Rs. ${Math.round(r.amount_paid || 0).toLocaleString('en-PK')}</td>
                    <td class="right pending">Rs. ${Math.round(r.remaining || 0).toLocaleString('en-PK')}</td>
                  </tr>
                `).join('')}
              </tbody>
              <tfoot>
                <tr class="total-row">
                  <td colspan="3"><strong>TOTAL PENDING</strong></td>
                  <td></td><td></td>
                  <td class="right pending"><strong>Rs. ${Math.round(person.pending).toLocaleString('en-PK')}</strong></td>
                </tr>
              </tfoot>
            </table>
            <div class="bill-footer">
              <div class="sig-box"><div class="sig-line"></div><div>Clerk</div></div>
              <div class="sig-box"><div class="sig-line"></div><div>${person.name}</div></div>
            </div>
            <div class="print-note">Generated by PrintDesk · ${billDate} · Area 9219</div>
          </div>
        `
      }).join('')
    }

    const win = window.open('', '_blank')
    win.document.write(`<!DOCTYPE html><html><head><title>Bill ${billDate}</title><style>
      *{box-sizing:border-box;margin:0;padding:0}
      body{font-family:'Segoe UI',Arial,sans-serif;font-size:12px;color:#1a1a18;background:#fff}
      .bill-page{max-width:210mm;margin:0 auto;padding:16mm 14mm;min-height:297mm}
      .page-break{page-break-after:always;height:0}
      .bill-header{text-align:center;border-bottom:2px solid #1a1a18;padding-bottom:12px;margin-bottom:14px}
      .org-name{font-size:16px;font-weight:800;letter-spacing:0.02em}
      .org-sub{font-size:11px;color:#666;margin-top:3px}
      .bill-title{font-size:12px;font-weight:700;letter-spacing:0.1em;margin-top:10px;text-transform:uppercase;color:#B8862E}
      .bill-meta{display:flex;justify-content:space-between;flex-wrap:wrap;gap:8px;font-size:12px;margin-bottom:14px;padding:8px 12px;background:#f8f8f6;border:1px solid #ddd;border-radius:6px}
      .bill-table{width:100%;border-collapse:collapse;font-size:11.5px;margin-bottom:20px}
      .bill-table th{background:#1a1a18;color:#fff;padding:7px 10px;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:0.04em;font-weight:700}
      .bill-table th.right,.bill-table td.right{text-align:right}
      .bill-table td{padding:7px 10px;border-bottom:1px solid #eee}
      .bill-table tr:nth-child(even) td{background:#fafaf8}
      .total-row td{background:#f0efe9!important;border-top:2px solid #1a1a18;padding:8px 10px}
      .pending{color:#c4401e;font-weight:700}
      .bill-footer{display:flex;justify-content:space-between;margin-top:32px;padding-top:20px}
      .sig-box{text-align:center;font-size:11px;color:#555}
      .sig-line{width:160px;border-bottom:1px solid #1a1a18;margin-bottom:6px}
      .print-note{text-align:center;font-size:10px;color:#aaa;margin-top:20px;border-top:1px solid #eee;padding-top:10px}
      @media print{body{margin:0}.bill-page{padding:12mm 10mm}.page-break{page-break-after:always}}
    </style></head><body>${billHtml}</body></html>`)
    win.document.close()
    setTimeout(() => win.print(), 500)
  }

  return (
    <div>
      <SectionTitle>Bill Generator</SectionTitle>
      <p style={{ color: 'var(--text-muted)', fontSize: 13, marginBottom: 20 }}>
        Generate bills to submit to the manager or share with staff. Prints as A4 PDF.
      </p>

      <div style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: 24, maxWidth: 520 }}>

        {/* Mode */}
        <div style={field}>
          <label style={label}>Who to bill</label>
          <div style={{ display: 'flex', gap: 8 }}>
            {[['individual', 'One Person'], ['all', `All Pending (${personsWithPending.length})`]].map(([val, lbl]) => (
              <button key={val} onClick={() => setMode(val)}
                style={{ flex: 1, padding: '9px', borderRadius: 'var(--radius-sm)', border: `1px solid ${mode === val ? 'var(--gold-border)' : 'var(--border)'}`, background: mode === val ? 'var(--gold-soft)' : 'var(--bg-elevated)', color: mode === val ? 'var(--gold)' : 'var(--text-secondary)', fontWeight: 700, fontSize: 13, cursor: 'pointer' }}>
                {lbl}
              </button>
            ))}
          </div>
        </div>

        {/* Person selector */}
        {mode === 'individual' && (
          <div style={field}>
            <label style={label}>Select Person</label>
            <select style={select} value={personId} onChange={e => setPersonId(e.target.value)}>
              <option value="">— Choose person —</option>
              {personRows.filter(r => r.billed > 0).map(r => (
                <option key={r.key} value={r.key}>
                  {r.name} {r.pending > 0 ? `— Due: ${rs(r.pending)}` : '(Fully paid)'}
                </option>
              ))}
            </select>
          </div>
        )}

        {/* Bill format */}
        <div style={field}>
          <label style={label}>Bill Format</label>
          <div style={{ display: 'flex', gap: 8 }}>
            {[['summary', '📋 Summary (1 page)'], ['detailed', '📄 With record details']].map(([val, lbl]) => (
              <button key={val} onClick={() => setBillScope(val)}
                style={{ flex: 1, padding: '9px', borderRadius: 'var(--radius-sm)', border: `1px solid ${billScope === val ? 'var(--gold-border)' : 'var(--border)'}`, background: billScope === val ? 'var(--gold-soft)' : 'var(--bg-elevated)', color: billScope === val ? 'var(--gold)' : 'var(--text-secondary)', fontWeight: 700, fontSize: 12.5, cursor: 'pointer' }}>
                {lbl}
              </button>
            ))}
          </div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 6 }}>
            {billScope === 'summary'
              ? 'Clean summary: Name, Balance Due, Signature. Best for submitting to manager.'
              : 'Shows each pending record per person. Best for sharing with the individual.'}
          </div>
        </div>

        {/* Preview info */}
        {mode === 'individual' && selectedPerson ? (
          <div style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '12px 14px', marginBottom: 16, fontSize: 13 }}>
            <div style={{ fontWeight: 700, marginBottom: 4 }}>{selectedPerson.name}</div>
            <div style={{ display: 'flex', gap: 16, color: 'var(--text-secondary)' }}>
              <span>Billed: <strong style={{ color: 'var(--text-primary)' }}>{rs(selectedPerson.billed)}</strong></span>
              <span>Received: <strong style={{ color: 'var(--success)' }}>{rs(selectedPerson.received)}</strong></span>
              <span>Due: <strong style={{ color: 'var(--danger)' }}>{rs(selectedPerson.pending)}</strong></span>
            </div>
          </div>
        ) : mode === 'all' && (
          <div style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '12px 14px', marginBottom: 16, fontSize: 13 }}>
            <div style={{ fontWeight: 700, marginBottom: 6 }}>{personsWithPending.length} persons with pending balances</div>
            {personsWithPending.map(p => (
              <div key={p.key} style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-secondary)', padding: '2px 0', fontSize: 12.5 }}>
                <span>{p.name}</span>
                <span style={{ color: 'var(--danger)', fontWeight: 700 }}>{rs(p.pending)}</span>
              </div>
            ))}
            <div style={{ borderTop: '1px solid var(--border)', marginTop: 8, paddingTop: 8, display: 'flex', justifyContent: 'space-between', fontWeight: 800, fontSize: 13 }}>
              <span>Total Pending</span>
              <span style={{ color: 'var(--danger)' }}>{rs(personsWithPending.reduce((s, p) => s + p.pending, 0))}</span>
            </div>
          </div>
        )}

        <button style={{ ...primaryBtn }} onClick={printBill} disabled={mode === 'individual' && !personId}>
          🖨️ Print / Save as PDF
        </button>

        <p style={{ fontSize: 11.5, color: 'var(--text-muted)', marginTop: 10, lineHeight: 1.6 }}>
          In the print dialog, choose <strong>"Save as PDF"</strong> to save a file instead of printing.
          Bill header can be customised in Settings.
        </p>
      </div>
    </div>
  )
}
